name: quizzler
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


 
  fonts:
    - family: Arvo
      fonts:
        - asset: fonts/Arvo-Regular.ttf
        
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        
  
